# Generated by Django 3.2.3 on 2021-05-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Post',
        ),
    ]
